# Generated by Django 3.0.7 on 2020-06-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
